// <auto-generated />
namespace Vira.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class change_malhizmet_malhizmetgrup1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_malhizmet_malhizmetgrup1));
        
        string IMigrationMetadata.Id
        {
            get { return "202108191357152_change_malhizmet_malhizmetgrup1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
