// <auto-generated />
namespace Vira.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_tableYekdem_remfield_addfield : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_tableYekdem_remfield_addfield));
        
        string IMigrationMetadata.Id
        {
            get { return "202106260859318_mig_tableYekdem_remfield_addfield"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
