// <auto-generated />
namespace Vira.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addColumnGelenGidenEv2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addColumnGelenGidenEv2));
        
        string IMigrationMetadata.Id
        {
            get { return "202107161059296_addColumnGelenGidenEv2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
